### ISSUE TITLE
radio frequenz stimmt nicht bei titan 4_0

### ISSUE THREAD

**Issue by unheilligkeit** [unheilligkeit/titan_missionstemplate#3]
Loadout Bug: SQL Titan 4-0 "Set radio" setzt die frequenzen falsch. Long range ist mit short range radio vertauscht

**Comment by Xavia1991** [comment]
Nicht reproduzierbar, config  stimmt und ingame auf SQL, FTL und Operator position kein Problem.

**Comment by unheilligkeit** [comment]
infos fehlen wie weshalb und warum darum geschlossen
