### ISSUE TITLE
Loadout SOTAC: Im Laserdesignator fehlen die Batterien

### ISSUE THREAD

**Issue by Rochhy** [unheilligkeit/titan_missionstemplate#5]
**Describe the bug**
Im Loadout der SOTACS fehlen im Laserdesignator die Batterien.

**To Reproduce**
1. Slotten als SOTAC in Titan 4.0
2. Ausrüstung wählen
3. Ins Inventar gehen
4. über Laser Designator Hovern 
5. oder alternativ Designator als Fernglas ausrüsten, anvisieren und versuchen den Laser zu aktivieren

**Expected behavior**
- Wenn der Laserdesignator als Fernglas ausgerüstet und anvisiert wird müsste der Laser aktiv werden (Anzeige oben Mitte)
- Wird im Inventar über den Laserdesignator gehovert müssten hier die Batterien mit angezeigt werden.

**Screenshots**
aktuell keine vorhanden.

**Slot(please complete the following information):**
 - Group: Titan 4.0
 - Loadout: SOTAC 

**Modpack/ missions(please complete the following information):**
 - Modpack: Titan Core Repo
 - Mission: 8th_SFG_BootCamp_V21-06-16_un
 - Server: Server

**Additional context**
Im Loadout CCT sind die Batterien mit im Laserdesignator ausgerüstet. 
Ich habe nur den SOTAC Slot von Titan 4.0 überprüft. Evtl besteht das Problem auch bei anderen Slots das Problem auch.
Problem tritt auch nach Wechsel von MFF Ausrüstung auf "Normal" Ausrüstung auf

**Comment by unheilligkeit** [comment]
ja stimmt die fehlen
