### ISSUE TITLE
Teleport ändert Team

### ISSUE THREAD

**Issue by Xavia1991** [unheilligkeit/titan_missionstemplate#6]
Teleport ändert das Team zum Ziel Team wenn man nicht zu seinem FTL porten kann, was für FTL selbst ein Problem ist. Teleport zu TITAN 4 hat nicht funktioniert.

**Comment by unheilligkeit** [comment]
telepoter sollte auch als leader zum team teleportieren

**Comment by Xavia1991** [comment]
braucht es denn den join des teams? finde es eher ein verwirrendes feature, da das ja nicht ziel der Funktion ist.

**Comment by unheilligkeit** [comment]
grundsätzlich ja und nein ist halt im demfall einfacher rauszufinden in welcher groupe der spieler ist wenn ich nähmlich die groupe als parameter übergeben will klappt das nicht eine standart gruppen name sieht so aus 
B titan_2_0
würde nur als string gehen aber es gibt keine funktion um string in group umzuwandeln 
gibt sich wege um das zu umgehen aber das war der einfachste
